name: SocialSpy
main: bav\socialspy\Main
version: 1.0.2
api: [3.5.1, 3.0.0]
load: POSTWORLD
author: Bavfalcon9
commands:
  socialspy:
    description: See all servers private messages
    usage: /socialspy
permissions:
  socialspy.command:
    description: Read private messages globally
    default: op